Colors fixed, button text in single mode fixed
inFullMobile/android-filepicker pull request #2
Opened 2017-09-12 07:21 UTC by lukaszwo

2017-09-12 07:21 UTC, MasterAccountIFM commented
--- JIRA LINKS ---

2017-09-19 09:16 UTC, rainqer requested changes

2017-09-19 09:16 UTC, rainqer commented on filepicker/src/main/java/com/github/angads25/filepicker/view/FilePickerDialog.java
> +                                             context.getResources().getString(R.string.choose_button_label)
very strange formatting

2017-09-19 09:16 UTC, rainqer commented on filepicker/src/main/java/com/github/angads25/filepicker/view/FilePickerDialog.java
> +                    getString(R.string.choose_button_label) : positiveBtnNameStr;
could one line but .... not a blocker

2017-09-19 09:16 UTC, rainqer commented on filepicker/src/main/java/com/github/angads25/filepicker/view/FilePickerDialog.java
> +                select.setText(positiveBtnNameStr);
zero is a positive number ?

2017-09-19 10:01 UTC, domhys commented on filepicker/src/main/java/com/github/angads25/filepicker/view/FilePickerDialog.java
> +                    getString(R.string.choose_button_label) : positiveBtnNameStr;
it won't fit in one line :/

2017-09-19 10:01 UTC, rainqer approved these changes

2017-09-19 10:10 UTC, merged